### ISSUE TITLE
Site launches locally from docker-compose.yml but doesn't fetch any results

### ISSUE THREAD

**Issue by magammon** [benfl3713/DepartureBoard#295]
**Describe the bug**
I have had no luck in hosting the site locally using the docker-compose.yml in the repository so I wrote my own. This service launches correctly but does not fetch any departures. I wonder if i have entered the RTT key in the wrong format. they have provided username and password as opposed to a single access key and I do not know how to format the key correctly. I have provided my RTT API password but this does not seem to work

**To Reproduce**
1. run `docker-compose up -d` using docker-compose.yml attached
2. Navigate to http://IPofcontainerserver:9005/KYN

**Expected behaviour**
See the departure boards for Keynsham.

**Actual behaviour**
'No Departures found for KYN' message shown

**Further steps taken**
I have used the container terminal to identify that there is a file `/config.xml` that despite me having the token in the docker-compose file did not have the key in. I have updated this file to `<Config><RealTimeTrainsToken>realtimetrainsapipassword here</RealTimeTrainsToken></Config>`

**Screenshots**
![Screenshot 2024-02-09 at 12 39 20](https://github.com/benfl3713/DepartureBoard/assets/149683839/d790fece-42cb-4726-af7d-4bed6fce720f)
![Screenshot 2024-02-09 at 12 39 27](https://github.com/benfl3713/DepartureBoard/assets/149683839/c46cc08c-a3e9-429e-b10d-fb46a93a7e8f)

**Additional context**
```
version: '3'

services:
  departure-board:
    container_name: ledboard
    image: benfl3713/departure-board:latest
    environment:
      - RealTimeTrainsToken=c675fe6045a96etttttt8d66fc1ac1df4d47e4ee
    ports:
      - `"9005:80"
```
